file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/llvm-hash.txt" TRITON_LLVM_HASH LIMIT_COUNT 1)
if(NOT EXISTS "${CMAKE_BINARY_DIR}/${TRITON_LLVM_HASH}.tar.gz")
  file(DOWNLOAD "https://github.com/llvm/llvm-project/archive/${TRITON_LLVM_HASH}.tar.gz" "${CMAKE_BINARY_DIR}/${TRITON_LLVM_HASH}.tar.gz")
endif()
file(SHA1 "${CMAKE_BINARY_DIR}/${TRITON_LLVM_HASH}.tar.gz" TRITON_LLVM_BINARY_HASH)
string(SUBSTRING "${TRITON_LLVM_HASH}" 0 8 TRITON_LLVM_SHORT_HASH)

hunter_config(LLVM
    VERSION "18.0.0-${TRITON_LLVM_SHORT_HASH}-triton"
    URL "${CMAKE_BINARY_DIR}/${TRITON_LLVM_HASH}.tar.gz"
    SHA1 "${TRITON_LLVM_BINARY_HASH}"
    CMAKE_ARGS
        LLVM_ENABLE_PROJECTS=clang;mlir
        LLVM_INSTALL_UTILS=ON
        LLVM_INCLUDE_TESTS=OFF
        LLVM_TARGETS_TO_BUILD=NVPTX;AMDGPU
)